## Data analysis
1) Which parameter of the house affect price the most? 
Some of those parameter has linear relation with the price, some not. some combination of parameter has affect on the price the most, some not. We need to find out.
We will analyse it by pairing each parameter  with the price. 
At the first step we consider only the numerical data
Find the MSE min, compare, get top 2 parameter has the MSE min

In [1]:
import numpy as np
import pandas as pd

df = pd.read_csv('./data/train.csv')
#Save the id columns:
df_id = df['Id']
df = df.drop(columns = 'Id')
df
#df_id.head(5)
#Check type of id type(df_id[0])
#type(df[3][0])

,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,FR2,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,Corner,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,FR2,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,60,RL,62.0,7917,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,8,2007,WD,Normal,175000
1456,20,RL,85.0,13175,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,NaN,MnPrv,NaN,0,2,2010,WD,Normal,210000
1457,70,RL,66.0,9042,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,NaN,GdPrv,Shed,2500,5,2010,WD,Normal,266500
1458,20,RL,68.0,9717,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,4,2010,WD,Normal,142125
1459,20,RL,75.0,9937,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,6,2008,WD,Normal,147500

Function to filter the numeric columns

In [2]:
def df_filter(df, type_of_col):
    return df.select_dtypes(include = type_of_col)
    #go over all column in df, get out only the type we need
    #for column in empDfObj:
   # Select column contents by column name using [] operator
   #columnSeriesObj = empDfObj[column]
   #print('Colunm Name : ', column)
   #print('Column Contents : ', columnSeriesObj.values)

In [31]:
#df_numeric.head(5)

#double check if needed
#for col in df_numeric: 
#print(df_numeric[col].dtype)
#filtering --> 37 columns
df_numeric_all = df_filter(df,np.number)
y = df_numeric_all['SalePrice']

#print(y)
#WILL CHOOSE THE LOTFRONTAGE AND LOTAREA WITHOUT REASONING
#df_n_frt_area = df_numeric_all[['LotFrontage','LotArea','SalePrice']]
#df_n_frt_area
ones = np.ones((y.shape[0],1))
df_add_ones = df_numeric_all.drop(columns='SalePrice')
df_add_ones['One'] = ones
df_add_ones_filtered = df_add_ones[['One','LotFrontage','LotArea']]
#type(df_add1)
#df_add_ones_filtered.to_csv('xbar.csv', header=None,index=False)
#df_train = pd.read_csv('xbar.csv', index_col=False)
Xbar = df_add_ones_filtered
#Xbar = Xbar.values.T
y = y.drop([0], axis =0)
#model parameter
# Calculating weights of the fitting line 
# Caution: Xbar.T is actually the X in the form: w = (X.Xt)pseuInverse.Xy
A = np.dot(Xbar.T, Xbar)
y
#b = np.dot(Xbar.T, y.T)
#w = np.dot(np.linalg.pinv(A), b)
#print('w = ', w)
Xbar
# Caanf phai drop header cho Xbar sau do lay values

      One  LotFrontage  LotArea
0     1.0         65.0     8450
1     1.0         80.0     9600
2     1.0         68.0    11250
3     1.0         60.0     9550
4     1.0         84.0    14260
...   ...          ...      ...
1455  1.0         62.0     7917
1456  1.0         85.0    13175
1457  1.0         66.0     9042
1458  1.0         68.0     9717
1459  1.0         75.0     9937

[1460 rows x 3 columns]

In [ ]:
#Define gradient
#w: model parameters value matrix
#Xbar: variable value matrix
#y: output vector
def grad(w,Xbar,y):
    N = Xbar.shape[0]
    return 1/N*Xbar.T.dot(Xbar.dot(w)-y)

#mse function
def mse(w, Xbar,y):
    N = Xbar.shape[0]
    return (1/2*N)*np.linalg.norm(y - Xbar.dot(w))**2

#Gradient Descent
#w_init: init param
#grad: gradient
#Xbar: variable value matrix
#y: output vector
#lr: learning rate
def grad_des(w_init, grad, Xbar, y, lr):
    w = [w_init]
    for i in range(1000):
        w_new = w[-1] - lr*grad(w[-1],Xbar,y)
        if np.linalg.norm(grad(w_new,Xbar,y))/len(w_new) < 1e-10
        break
        w.append(w_new)
    return (w,i)

#